sudo: false
language: go
go:
  - 1.6
  - 1.7
  - tip

services:
  - mysql

env:
  - PATH=/home/travis/gopath/bin:$PATH

before_install:
  - go get github.com/golang/lint/golint
  - go get github.com/mitchellh/gox
  - go get github.com/jteeuwen/go-bindata/...
  - make deps

script:
  - mysql -e 'create database test_techradar'
  - make test
  - go-bindata -o assets.go dist/
  - gox -ldflags "-X main.Version=$TRAVIS_BUILD_NUMBER" -output "tech-radar_{{.OS}}_{{.Arch}}" -osarch="linux/amd64"
  - cp tech-radar_linux_amd64 tech-radar
  - gzip tech-radar_linux_amd64
  - zip tech-radar_linux_amd64_latest.zip tech-radar
  - mkdir -p dist2 release
  - cp tech-radar_linux_amd64_latest.zip dist2/
  - cp tech-radar_linux_amd64.gz dist2/tech-radar_linux_amd64_latest.gz
  - cp tech-radar_linux_amd64.gz release/tech-radar_linux_amd64_$(git describe --tags).gz

deploy:
  - provider: s3
    access_key_id: AKIAJWN36CZNBCQXFFTQ
    secret_access_key:
      secure: XuOzbrACI8UqGWVWG3FZ8sgCW+icQTv3svnJaqxZXkxXhwdwYRey4tUru3m9IT4015KwWtuEwYxD6F+sQ0XKihNtO4d04eaoaHKY1rTKhHS4vB53bdW8ZMBxcT2kNGvuTOPW6ijuZKNiFVaql/D7Blx7Q/RTtyYVCHzZ8xFkXNYQBWMD9R5JHhqZnD7uaKH9Q6r0bamgGITM3WPbwV/hz7CoCjsmLjRKTyjai0Ez0Pq8NQ3EaT60PuQEqpelWN7aTne5ktkDuMnvvvEKQs1pGiHclPzNFxngI3VesIEMImURA3n9k9uQO4IHeWqIYagw8bfE4g7hI+iD9sRY0+GvBZMZJVliqUGG1nCNfAVOTx6SYMGeoxyW6NW2P/bbO7S/LAY0nikjrfUKLFjFlRKcg1tT1JERCWRuCdoyv34lHbl32lg92nUmR3MZDTfP6A+O6XIoxgIdJrSy4cjcBqOK4Yp66/foyBZLUgopX4cWqBrguN+HMzyJUquEkE172Li6XHrqEHSEciQF+umNfD8ZknR0n1yYHpIP2n4oAuxnMmf8MBG5UfGkiLTIYUtqoEPGZPVYid5f386plAXGaZpr9XhrxlDSLjyg/8/5qEfLMh5KsO9cB5xspK8dSw7UfOuOyDFAf8DmjMCKSJrc7I2/7vu33/Vmdw5LWiN/zdSiN0k=
    bucket: dl.fligl.io
    skip_cleanup: true
    local-dir: dist2
    upload-dir: artifacts/tech-radar
    acl: public_read
  - provider: s3
    access_key_id: AKIAJWN36CZNBCQXFFTQ
    secret_access_key:
      secure: XuOzbrACI8UqGWVWG3FZ8sgCW+icQTv3svnJaqxZXkxXhwdwYRey4tUru3m9IT4015KwWtuEwYxD6F+sQ0XKihNtO4d04eaoaHKY1rTKhHS4vB53bdW8ZMBxcT2kNGvuTOPW6ijuZKNiFVaql/D7Blx7Q/RTtyYVCHzZ8xFkXNYQBWMD9R5JHhqZnD7uaKH9Q6r0bamgGITM3WPbwV/hz7CoCjsmLjRKTyjai0Ez0Pq8NQ3EaT60PuQEqpelWN7aTne5ktkDuMnvvvEKQs1pGiHclPzNFxngI3VesIEMImURA3n9k9uQO4IHeWqIYagw8bfE4g7hI+iD9sRY0+GvBZMZJVliqUGG1nCNfAVOTx6SYMGeoxyW6NW2P/bbO7S/LAY0nikjrfUKLFjFlRKcg1tT1JERCWRuCdoyv34lHbl32lg92nUmR3MZDTfP6A+O6XIoxgIdJrSy4cjcBqOK4Yp66/foyBZLUgopX4cWqBrguN+HMzyJUquEkE172Li6XHrqEHSEciQF+umNfD8ZknR0n1yYHpIP2n4oAuxnMmf8MBG5UfGkiLTIYUtqoEPGZPVYid5f386plAXGaZpr9XhrxlDSLjyg/8/5qEfLMh5KsO9cB5xspK8dSw7UfOuOyDFAf8DmjMCKSJrc7I2/7vu33/Vmdw5LWiN/zdSiN0k=
    bucket: dl.fligl.io
    skip_cleanup: true
    local-dir: release
    upload-dir: artifacts/tech-radar
    acl: public_read
    on:
      tags: true
  - provider: releases
    api_key:
      secure: vqwo7VYUfjgwW9fyvAmM0UhUegoxnKXY1ki/Z7PHt4wDGpzxVDrzDCix44FFHBl9ejhnfvTr7vb9mEDNaK6CucMs13HrwhwSD8bkr70suMpifql/L4n60jYc4XgLnBS9noIpks234nCsGXJnSmQpBAZA/UdbTuKt48d4vu1NAGqAGJlc1W8/va/BuSzWbDu6UlHQHinpD43AFhMS3WmnHO6oUOEcFySisSHxMrKfiCil3fb0w0J0rDuK5vaVxsljF/TjpTTf+RB1rhCrnZMudrH3QlT7byRvvk9QyKzMFyuiE9Ce1JiDULE7OCyK9dBSdSWdNTyJGa3e4HjvrwQhmmzqoVo15nOD0nfOpFHnp/zdNNPjt4kyx0FgNgQ6l9FhXGIBv+C0mRExOHHX4ZgatwWFVI08kj+qUi7QchZjfuGFTFkvtC09zfM6BgHZPGq7PUXlJhmGW8C5Ln1EonE3lnn8u5QWjm4FPdMMRfiissBDrx/sNM2JJn+qrt6uF95sXv+Ya0TX+qMEpLlxebyFEmTyKUTMR++KZQFcOzx+/aIVgv3jCJV1g7AhrIf0ZWg7MA62vJpDW59bJL9h9N+o47wWdNtWJQBG4+Jh1OwqYaBdqaUNn9aTfmzXnl6SRRQEPfYq0zv7XF7KfyEOYpPNCa87zN5c61T2oR0ga2gdo78=
    file: tech-radar_linux_amd64.gz
    on:
      tags: true
